global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "kubernetes"
    scrape_interval: "10s"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - target:9100
